"use strict";
/* ════════════════════════════════════════════════════════════════════════
   Wings Ahead — syllabus catalogue.  GENERATED FILE — DO NOT EDIT.
   ────────────────────────────────────────────────────────────────────────
   WA_ITEMS   — the printed gradesheet items per category, from the FDMS
                Phase II syllabus item list (data/observations/master_index.json
                → contact / instrument / formation / vfr_navigation).
   WA_SORTIES — the Phase II sortie codes per category, from the FDMS
                flow chart (data/flowchart2.json → sorties[]).
   Regenerate with:  python tools/gen-items-catalog.py

   WA_ITEMS.categories[].items[]
     id    — syllabus item id (e.g. contact-12)
     n     — printed item number(s), '12–20' when the printed item spans rows,
             null for CRM (no numbered row)
     name  — the printed item name, verbatim
   WA_SORTIES[categoryId][]
     c     — sortie code (e.g. C4302)      n — printed sortie name
     b     — band: 'flights' | 'fs' (simulator)   k — checkride?

   117 items and 133 sortie codes across 4 categories,
   generated from master_index 2026-08-08T22:10:34 / flow chart 2026-08-09.
   ════════════════════════════════════════════════════════════════════════ */
var WA_ITEMS = {
  source: "FDMS Phase II syllabus item list (master_index.json, 2026-08-08T22:10:34)",
  total: 117,
  categories: [
    { id: "contact", label: "Contact", items: [
      { id: "contact-01", n: "01", name: "GROUND PROCEDURES" },
      { id: "contact-02", n: "02", name: "TAKE OFF" },
      { id: "contact-03", n: "03", name: "DEPARTURE / TRANSITION TO FLIGHT AREAS" },
      { id: "contact-04", n: "04", name: "AREA AWARENESS" },
      { id: "contact-05", n: "05", name: "BASIC A/C CONTROL" },
      { id: "contact-06", n: "06", name: "G –AWARENESS" },
      { id: "contact-07", n: "07", name: "SLOW FLIGHT" },
      { id: "contact-08", n: "08", name: "POWER ON / ELP STALLS" },
      { id: "contact-09", n: "09", name: "TRAFFIC PATTERN STALLS" },
      { id: "contact-10", n: "10", name: "SPIN PREVENTION /SPIN RECOVERY" },
      { id: "contact-11", n: "11", name: "UNUSUAL ATTITUDES RECOVERY" },
      { id: "contact-12", n: "12–20", name: "PRECISION - AEROBATIC MANEUVERS" },
      { id: "contact-21", n: "21", name: "DESCENT - TRAFFIC PATTERN ENTRY" },
      { id: "contact-22", n: "22", name: "AIRPORT TRAFFIC PATTERN" },
      { id: "contact-23", n: "23, 25, 27, 32", name: "LANDING PATTERN (NORMAL, NO FLAP, FLAP T/O - AΟA)" },
      { id: "contact-24", n: "24, 26, 28, 33", name: "LANDING (FLAPS LDG - FLAPS UP - FLAPS Τ/Ο - ELP - AΟA)" },
      { id: "contact-29", n: "29", name: "STRAIGHT-IN (FLAPS LDG, FLAPS UP, FLAPS Τ/Ο)." },
      { id: "contact-30", n: "30", name: "EMERGENCY LANDING PATTERN (ELP)" },
      { id: "contact-34", n: "34", name: "GO AROUND" },
      { id: "contact-35", n: "35", name: "CLOSED PATTERN" },
      { id: "contact-36", n: "36", name: "CLEARING" },
      { id: "contact-37", n: "37", name: "RADIO COMMUNICATION" },
      { id: "contact-38", n: "38", name: "AIRMANSHIP" },
      { id: "contact-39", n: "39", name: "EMERGENCY PROCEDURES" },
      { id: "contact-40", n: "40", name: "GENERAL KNOWLEDGE" },
      { id: "contact-41", n: "41", name: "SPECIAL REQUIREMENTS" },
      { id: "contact-crm", n: null, name: "CRM" },
    ] },
    { id: "instrument", label: "Instrument", items: [
      { id: "instrument-01", n: "01", name: "GROUND PROCEDURES" },
      { id: "instrument-02", n: "02", name: "TAKE OFF" },
      { id: "instrument-03", n: "03", name: "STANDARD INSTRUMENT DEPARTURE (SID)" },
      { id: "instrument-04", n: "04", name: "BASIC A/C CONTROL" },
      { id: "instrument-05", n: "05", name: "STEEP TURNS" },
      { id: "instrument-06", n: "06", name: "AIRSPEED CHANGES" },
      { id: "instrument-07", n: "07–09", name: "CONSTANT AIRSPEED - CONSTANT RATE CLIMBS / DESCENTS AND VERTICAL \"S\"" },
      { id: "instrument-10", n: "10", name: "UNUSUAL ATTITUDES RECOVERY" },
      { id: "instrument-11", n: "11", name: "CONFIDENCE MANEUVERS" },
      { id: "instrument-12", n: "12", name: "COURSE INTERCEPTS" },
      { id: "instrument-13", n: "13", name: "MAINTAINING COURSE" },
      { id: "instrument-14", n: "14", name: "ARC INTERCEPT" },
      { id: "instrument-15", n: "15", name: "MAINTAINING ARC" },
      { id: "instrument-16", n: "16", name: "POINT TO POINT" },
      { id: "instrument-17", n: "17", name: "HOLDING" },
      { id: "instrument-18", n: "18", name: "INSTRUMENT DESCENT (PENETRATION)" },
      { id: "instrument-19", n: "19", name: "EN-ROUTE DESCENT" },
      { id: "instrument-20", n: "20", name: "VOR / TACAN APPROACH" },
      { id: "instrument-21", n: "21", name: "ILS APPROACH" },
      { id: "instrument-22", n: "22", name: "LOCALIZER APPROACH" },
      { id: "instrument-23", n: "23", name: "GCA APPROACH (ASR)" },
      { id: "instrument-24", n: "24", name: "GCA APPROACH (PAR)" },
      { id: "instrument-25", n: "25", name: "GCA APPROACH (GYRO OUT)" },
      { id: "instrument-26", n: "26", name: "STANDBY INSTRUMENTS APPROACH" },
      { id: "instrument-27", n: "27", name: "CIRCLING APPROACH" },
      { id: "instrument-28", n: "28", name: "LANDING" },
      { id: "instrument-29", n: "29", name: "MISSED APPROACH" },
      { id: "instrument-30", n: "30–33", name: "RADIO COMMUNICATION, AIRMANSHIP, EMERGENCY PROCEDURES, GENERAL KNOWLEDGE." },
      { id: "instrument-34", n: "34", name: "SPECIAL REQUIREMENTS" },
      { id: "instrument-crm", n: null, name: "CRM" },
    ] },
    { id: "formation", label: "Formation", items: [
      { id: "formation-01", n: "01–02", name: "TAKE OFF (FORMATION - INTERVAL)" },
      { id: "formation-03", n: "03", name: "DEPARTURE" },
      { id: "formation-04", n: "04", name: "IN FLIGHT PLANNING / FORMATION CONSISTENCY" },
      { id: "formation-05", n: "05", name: "RETURN / DESCENT / TRAFFIC PATTERN ENTRY" },
      { id: "formation-06", n: "06", name: "FORMATION APPROACH" },
      { id: "formation-07", n: "07", name: "FORMATION TAKE OFF" },
      { id: "formation-08", n: "08", name: "INTERVAL TAKE OFF" },
      { id: "formation-09", n: "09", name: "TURNING REJOIN" },
      { id: "formation-10", n: "10", name: "STRAIGHT AHEAD REJOIN" },
      { id: "formation-11", n: "11", name: "OVERSHOOT" },
      { id: "formation-12", n: "12", name: "BREAK OUT" },
      { id: "formation-13", n: "13", name: "FORMATION APPROACH." },
      { id: "formation-14", n: "14", name: "MISSION PLANNING / BRIEFING." },
      { id: "formation-15", n: "15", name: "GROUND PROCEDURES." },
      { id: "formation-16", n: "16", name: "PITCH OUT / SPACING" },
      { id: "formation-17", n: "17", name: "FINGERTIP" },
      { id: "formation-18", n: "18", name: "ROUTE / FIGHTING WING FORMATION" },
      { id: "formation-19", n: "19", name: "ECHELON TURN (AS WINGMAN)" },
      { id: "formation-20", n: "20", name: "CROSS UNDER" },
      { id: "formation-21", n: "21", name: "LEAD CHANGE" },
      { id: "formation-22", n: "22", name: "CLOSE TRAIL" },
      { id: "formation-23", n: "23", name: "EXTENDED TRAIL" },
      { id: "formation-24", n: "24", name: "TACTICAL FORMATION" },
      { id: "formation-24b", n: "24–28", name: "TACTICAL TURNS DELAY 90°, DELAY 45°, IN PLACE, CROSS / HOOK / SHACKLE/ CHECK TURNS" },
      { id: "formation-29", n: "29", name: "BASIC A/C - FORMATION CONTROL" },
      { id: "formation-30", n: "30", name: "LANDING PATTERN" },
      { id: "formation-31", n: "31", name: "LANDING" },
      { id: "formation-32", n: "32", name: "VISUAL SIGNALS" },
      { id: "formation-33", n: "33", name: "CLEARING" },
      { id: "formation-34", n: "34", name: "RADIO COMMUNICATION" },
      { id: "formation-35", n: "35", name: "AIRMANSHIP" },
      { id: "formation-36", n: "36", name: "EMERGENCY PROCEDURES" },
      { id: "formation-37", n: "37", name: "GENERAL KNOWLEDGE" },
      { id: "formation-crm", n: null, name: "CRM" },
    ] },
    { id: "vfr_navigation", label: "VFR Navigation", items: [
      { id: "vfr_navigation-01", n: "01", name: "MISSION PLANNING / BRIEFING - DEBRIEFING" },
      { id: "vfr_navigation-02", n: "02", name: "GROUND PROCEDURES" },
      { id: "vfr_navigation-03", n: "03", name: "TAKEOFF" },
      { id: "vfr_navigation-04", n: "04", name: "VFR DEPARTURE / SID" },
      { id: "vfr_navigation-05", n: "05", name: "BASIC A/C CONTROL / WINGMAN CONSIDERATION" },
      { id: "vfr_navigation-06", n: "06", name: "IN-FLIGHT PLANNING / FORMATION INTERGRITY" },
      { id: "vfr_navigation-07", n: "07", name: "FINGERTIP" },
      { id: "vfr_navigation-08", n: "08", name: "TACTICAL FORMATION" },
      { id: "vfr_navigation-09", n: "09", name: "TACTICAL TURNS" },
      { id: "vfr_navigation-10", n: "10", name: "MAINTAIN TRACK" },
      { id: "vfr_navigation-11", n: "11", name: "MAP READING" },
      { id: "vfr_navigation-12", n: "12", name: "PILOTAGE" },
      { id: "vfr_navigation-13", n: "13", name: "NAVIGATION WITH GPS" },
      { id: "vfr_navigation-14", n: "14", name: "VFR ARRIVAL / TRAFFIC PATTERN ENTRY" },
      { id: "vfr_navigation-15", n: "15", name: "INSTRUMET PROCEDURES" },
      { id: "vfr_navigation-16", n: "16", name: "FORMATION APPROACH" },
      { id: "vfr_navigation-17", n: "17", name: "TRAFFIC PATTERN PROCEDURES" },
      { id: "vfr_navigation-18", n: "18", name: "OVERHEAD PATTERN" },
      { id: "vfr_navigation-19", n: "19", name: "LANDING" },
      { id: "vfr_navigation-20", n: "20", name: "INSTRUMENT PROCEDURES" },
      { id: "vfr_navigation-21", n: "21", name: "CLEARING" },
      { id: "vfr_navigation-22", n: "22", name: "COMMUNICATION" },
      { id: "vfr_navigation-23", n: "23", name: "AIRMANSHIP" },
      { id: "vfr_navigation-24", n: "24", name: "EMERGENCY PROCEDURES" },
      { id: "vfr_navigation-25", n: "25", name: "GENERAL KNOWLEDGE" },
      { id: "vfr_navigation-crm", n: null, name: "CRM" },
    ] }
  ],
};

/* Phase II sortie codes per category — the FAIL / ALMOST GOOD flight-code
   picker (searchable; free text is always accepted as a fallback). */
var WA_SORTIES = {
  "contact": [
    { c: "B1001", n: "Basic exercises (Familiarization) — normal procedures", b: "fs" },
    { c: "B1002", n: "Basic exercises (Familiarization) — normal procedures", b: "fs" },
    { c: "C1101", n: "Contact — basic A/C control and familiarization with flight characteristics", b: "fs" },
    { c: "C2101", n: "Emergency Procedures", b: "fs" },
    { c: "C2201", n: "Contact — fundamental flight maneuvers", b: "fs" },
    { c: "C2202", n: "Contact — fundamental flight maneuvers", b: "fs" },
    { c: "C2301", n: "Emergency Procedures training in a mission profile", b: "fs" },
    { c: "C2302", n: "Emergency Procedures training in a mission profile", b: "fs" },
    { c: "C2401", n: "Contact — fundamental flight maneuvers and landings", b: "fs" },
    { c: "C2402", n: "Contact — fundamental flight maneuvers and landings", b: "fs" },
    { c: "C2403", n: "Contact — fundamental flight maneuvers and landings", b: "fs" },
    { c: "C2501", n: "Emergency Procedures training in a mission profile", b: "fs" },
    { c: "C2502", n: "Emergency Procedures training in a mission profile", b: "fs" },
    { c: "C2503", n: "Emergency Procedures training in a mission profile", b: "fs" },
    { c: "C2601", n: "Contact — fundamental flight maneuvers and landings", b: "fs" },
    { c: "C2602", n: "Contact — fundamental flight maneuvers and landings", b: "fs" },
    { c: "C2603", n: "Contact — fundamental flight maneuvers and landings", b: "fs" },
    { c: "C2604", n: "Contact — fundamental flight maneuvers and landings", b: "fs" },
    { c: "C4101", n: "Contact – Familiarization", b: "flights" },
    { c: "C4201", n: "Contact – fundamental flight maneuvers", b: "flights" },
    { c: "C4202", n: "Contact – fundamental flight maneuvers", b: "flights" },
    { c: "C4203", n: "Contact – fundamental flight maneuvers", b: "flights" },
    { c: "C4301", n: "Contact – Basic Maneuvers", b: "flights" },
    { c: "C4302", n: "Contact – Basic Maneuvers", b: "flights" },
    { c: "C4303", n: "Contact – Basic Maneuvers", b: "flights" },
    { c: "C4401", n: "Contact – Basic Maneuvers", b: "flights" },
    { c: "C4402", n: "Contact – Basic Maneuvers", b: "flights" },
    { c: "C4403", n: "Contact – Basic Maneuvers", b: "flights" },
    { c: "C4590", n: "Contact checkride", b: "flights", k: true },
    { c: "C4601", n: "Contact – Overhead Traffic Pattern", b: "flights" },
    { c: "C4602", n: "Contact – Overhead Traffic Pattern", b: "flights" },
    { c: "C4790", n: "Contact checkride for SOLO (C4790) and 1st SOLO (C4791)", b: "flights", k: true },
    { c: "C4791", n: "Contact checkride for SOLO (C4790) and 1st SOLO (C4791)", b: "flights" },
    { c: "C4801", n: "Contact – Basic/Advanced Maneuvers", b: "flights" },
    { c: "C4802", n: "Contact – Basic/Advanced Maneuvers", b: "flights" },
    { c: "C4803", n: "Contact – Basic/Advanced Maneuvers", b: "flights" },
    { c: "C4804", n: "Contact – Basic/Advanced Maneuvers", b: "flights" },
    { c: "C4901", n: "Contact – Basic/Advanced Maneuvers", b: "flights" },
    { c: "C4902", n: "Contact – Basic/Advanced Maneuvers", b: "flights" },
    { c: "C4903", n: "Contact – Basic/Advanced Maneuvers", b: "flights" },
    { c: "C4904", n: "Contact – Basic/Advanced Maneuvers", b: "flights" },
    { c: "C4905", n: "Contact – Basic/Advanced Maneuvers", b: "flights" },
    { c: "C5090", n: "Contact Checkride", b: "flights", k: true },
    { c: "C5101", n: "Contact – Basic/Advanced Maneuvers", b: "flights" },
    { c: "C5102", n: "Contact – Basic/Advanced Maneuvers", b: "flights" },
    { c: "C5201", n: "Contact – Basic/Advanced Maneuvers", b: "flights" },
    { c: "C5202", n: "Contact – Basic/Advanced Maneuvers", b: "flights" },
    { c: "C5203", n: "Contact – Basic/Advanced Maneuvers", b: "flights" },
    { c: "C5204", n: "Contact – Basic/Advanced Maneuvers", b: "flights" },
    { c: "C5301", n: "Contact – Basic/Advanced Maneuvers", b: "flights" },
    { c: "C5302", n: "Contact – Basic/Advanced Maneuvers", b: "flights" },
    { c: "C5303", n: "Contact – Basic/Advanced Maneuvers", b: "flights" },
    { c: "C5304", n: "Contact – Basic/Advanced Maneuvers", b: "flights" },
    { c: "C5490", n: "Final Contact Checkride", b: "flights", k: true },
  ],
  "instrument": [
    { c: "I3101", n: "Basic Instruments procedures", b: "fs" },
    { c: "I3102", n: "Basic Instruments procedures", b: "fs" },
    { c: "I3201", n: "Basic and Advanced Instruments", b: "fs" },
    { c: "I3202", n: "Basic and Advanced Instruments", b: "fs" },
    { c: "I3203", n: "Basic and Advanced Instruments", b: "fs" },
    { c: "I3301", n: "Basic and Advanced Instruments", b: "fs" },
    { c: "I3302", n: "Basic and Advanced Instruments", b: "fs" },
    { c: "I3303", n: "Basic and Advanced Instruments", b: "fs" },
    { c: "I3304", n: "Basic and Advanced Instruments", b: "fs" },
    { c: "I3401", n: "IFR Navigation", b: "fs" },
    { c: "I3402", n: "IFR Navigation", b: "fs" },
    { c: "I3403", n: "IFR Navigation", b: "fs" },
    { c: "I3404", n: "IFR Navigation", b: "fs" },
    { c: "I3501", n: "IFR Navigation", b: "fs" },
    { c: "I3502", n: "IFR Navigation", b: "fs" },
    { c: "I3503", n: "IFR Navigation", b: "fs" },
    { c: "I3504", n: "IFR Navigation", b: "fs" },
    { c: "I3601", n: "Night IFR Navigation", b: "fs" },
    { c: "I4101", n: "Basic Instrument", b: "flights" },
    { c: "I4102", n: "Basic Instrument", b: "flights" },
    { c: "I4201", n: "Advanced Instrument", b: "flights" },
    { c: "I4202", n: "Advanced Instrument", b: "flights" },
    { c: "I4301", n: "Advanced Instrument", b: "flights" },
    { c: "I4302", n: "Advanced Instrument", b: "flights" },
    { c: "I4490", n: "Instrument Checkride", b: "flights", k: true },
    { c: "I4501", n: "IFR navigation flights through airways or Approach to Approach", b: "flights" },
    { c: "I4502", n: "IFR navigation flights through airways or Approach to Approach", b: "flights" },
    { c: "I4601", n: "IFR navigation flights through airways or Approach to Approach", b: "flights" },
    { c: "I4602", n: "IFR navigation flights through airways or Approach to Approach", b: "flights" },
    { c: "I4603", n: "IFR navigation flights through airways or Approach to Approach", b: "flights" },
    { c: "I4701", n: "Night IFR navigation flight through airways", b: "flights" },
    { c: "I4890", n: "Final Instruments Checkride", b: "flights", k: true },
  ],
  "formation": [
    { c: "F3101", n: "Two-ship Formation", b: "fs" },
    { c: "F3102", n: "Two-ship Formation", b: "fs" },
    { c: "F3201", n: "Two-ship Formation", b: "fs" },
    { c: "F3202", n: "Two-ship Formation", b: "fs" },
    { c: "F3203", n: "Two-ship Formation", b: "fs" },
    { c: "F4101", n: "Two-ship Formation", b: "flights" },
    { c: "F4102", n: "Two-ship Formation", b: "flights" },
    { c: "F4103", n: "Two-ship Formation", b: "flights" },
    { c: "F4104", n: "Two-ship Formation", b: "flights" },
    { c: "F4201", n: "Two-ship Formation", b: "flights" },
    { c: "F4202", n: "Two-ship Formation", b: "flights" },
    { c: "F4203", n: "Two-ship Formation", b: "flights" },
    { c: "F4204", n: "Two-ship Formation", b: "flights" },
    { c: "F4301", n: "Two-ship Formation", b: "flights" },
    { c: "F4302", n: "Two-ship Formation", b: "flights" },
    { c: "F4303", n: "Two-ship Formation", b: "flights" },
    { c: "F4304", n: "Two-ship Formation", b: "flights" },
    { c: "F4305", n: "Two-ship Formation", b: "flights" },
    { c: "F4306", n: "Two-ship Formation", b: "flights" },
    { c: "F4401", n: "Two-ship Formation (Closed and Tactical)", b: "flights" },
    { c: "F4402", n: "Two-ship Formation (Closed and Tactical)", b: "flights" },
    { c: "F4403", n: "Two-ship Formation (Closed and Tactical)", b: "flights" },
    { c: "F4404", n: "Two-ship Formation (Closed and Tactical)", b: "flights" },
    { c: "F4501", n: "Two-ship Formation (Closed and Tactical)", b: "flights" },
    { c: "F4502", n: "Two-ship Formation (Closed and Tactical)", b: "flights" },
    { c: "F4503", n: "Two-ship Formation (Closed and Tactical)", b: "flights" },
    { c: "F4690", n: "Final Formation Checkride", b: "flights", k: true },
  ],
  "vfr_navigation": [
    { c: "N2101", n: "VFR Navigation (Medium Level)", b: "fs" },
    { c: "N2201", n: "VFR Navigation (Low Level)", b: "fs" },
    { c: "N2202", n: "VFR Navigation (Low Level)", b: "fs" },
    { c: "N2301", n: "VFR Navigation (Low Level)", b: "fs" },
    { c: "N2302", n: "VFR Navigation (Low Level)", b: "fs" },
    { c: "N2303", n: "VFR Navigation (Low Level)", b: "fs" },
    { c: "N2304", n: "VFR Navigation (Low Level)", b: "fs" },
    { c: "N4101", n: "VFR Navigation (Medium Altitude)", b: "flights" },
    { c: "N4102", n: "VFR Navigation (Medium Altitude)", b: "flights" },
    { c: "N4201", n: "VFR Navigation (Low Altitude)", b: "flights" },
    { c: "N4202", n: "VFR Navigation (Low Altitude)", b: "flights" },
    { c: "N4301", n: "VFR Navigation (Low Altitude)", b: "flights" },
    { c: "N4302", n: "VFR Navigation (Low Altitude)", b: "flights" },
    { c: "N4401", n: "Medium Level VFR Navigation (Two Ship Formation)", b: "flights" },
    { c: "N4402", n: "Medium Level VFR Navigation (Two Ship Formation)", b: "flights" },
    { c: "N4403", n: "Medium Level VFR Navigation (Two Ship Formation)", b: "flights" },
    { c: "N4501", n: "Low Level VFR Navigation (Two Ship Formation)", b: "flights" },
    { c: "N4502", n: "Low Level VFR Navigation (Two Ship Formation)", b: "flights" },
    { c: "N4503", n: "Low Level VFR Navigation (Two Ship Formation)", b: "flights" },
    { c: "N4690", n: "Final Navigation Checkride", b: "flights", k: true },
  ]
};
